version: '3.3'

services:
  app:
    build: &build
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_URL: &db_default ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_URL: ${ADMIN_URL}
      DEBUG: ${DEBUG}
    command: gunicorn yourwall.wsgi:application --config='/gunicorn.py' --reload
    volumes:
      - .:/home/docker/code/app/
    ports:
      - ${PORT}:80
    depends_on:
      - postgres

  postgres:
    image: 'postgres:10.6'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  migrate:
    build: *build
    environment:
      DATABASE_URL: *db_default
      SECRET_KEY: ${SECRET_KEY}
    command: python manage.py migrate
    depends_on:
      - postgres

  redis:
    image: "redis:5-alpine"
